import './globals.css'
import { ClientLayout } from '@/components/client-layout'
import { Navbar } from '@/components/navbar'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import type { ReactNode } from 'react'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground antialiased`}
			>
				<ClientLayout>
					<Navbar />
					<div className="mx-auto max-w-7xl p-8">{children}</div>
				</ClientLayout>
			</body>
		</html>
	)
}
